version: '3.7'
services:
  web:
    image: nginx:alpine
    # restart: always
    container_name: nginx_ujian
    ports:
     - "80:80"
    volumes:
      - "./:/var/www/html"
      - "./site.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - php
  php:
    image: bitnami/php-fpm
    # restart: always
    container_name: php_ujian
    expose:
     - 9000
    volumes:
      - "./:/var/www/html"
      - "./php-fpm.conf:/opt/bitnami/php/etc/php-fpm.conf"
      - "./php-cust.ini:/opt/bitnami/php/etc/php.ini"
    depends_on:
      - db
  db:
    image: bitnami/mariadb:latest
    # restart: always
    container_name: db_ujian
    ports:
        - "3306:3306"
    expose:
        - "3306"
    environment:
        ALLOW_EMPTY_PASSWORD: 'yes'
        MARIADB_ROOT_USER: 'root'
        # MARIADB_ROOT_PASSWORD: 'root'
        MARIADB_DATABASE: 'ujian_dbs'
  # pdf:
    # image: ciricihq/wkhtmltopdf-aas
    # restart: always
    # container_name: wkhtmltopdf
# volumes:
  # pgsql:
    # name: pgsql_ujian
